# Generated by Django 4.2.5 on 2023-10-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('type', models.CharField(default='R', max_length=1)),
                ('address', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='A', max_length=2)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
